# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bb4b40a1147fc22d3ef6c5f7409f41f9"
name = "Okkoverse"
handle = "okkoverse-1"
application_url = "https://dollar-stating-surprising-berkeley.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,write_products"

[auth]
redirect_urls = ["https://dollar-stating-surprising-berkeley.trycloudflare.com/auth/callback", "https://dollar-stating-surprising-berkeley.trycloudflare.com/auth/shopify/callback", "https://dollar-stating-surprising-berkeley.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
